name: build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    # - name: Install dependencies
    #   run: python -m pip install .[actions] --upgrade pip
    - name: Create environment
      run: |
        wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        chmod +x miniconda.sh
        ./miniconda.sh -b
        export PATH=/home/runner/miniconda3/bin:$PATH
        conda update --yes conda
        conda env create --name tbdenv -f environment.yml
        conda info         
        $CONDA/bin/activate tbdenv
        conda install --yes coverage coveralls flake8
    # - name: Activate environment
    # conda activate tbdenv
      # run: $CONDA/bin/conda init zsh
    # - name: Initialize shell
    #   run: $CONDA/bin/conda activate tbdenv
    - name: Install packages
      run: python -m pip install .[dev] --upgrade pip
      # run: python setup.py install
    - name: Test with pytest
      run: pytest
    - name: Flake
      run: |
        pip install flake8
        flake8
    # - name: Build package distribution
    #   if: startsWith(github.ref, 'refs/tags')
    #   run: |
    #     python -m pip install build 
    #     python -m build --sdist --wheel --outdir dist/ .
    # - name: Publish package distribution to PyPI
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     skip_existing: true
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}